import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'core/constants/app_constants.dart';
import 'core/enums/payment_method.dart';
import 'core/enums/recurring_type.dart';
import 'core/theme/app_theme.dart';
import 'data/models/app_settings_model.dart';
import 'data/models/budget_model.dart';
import 'data/models/category_model.dart';
import 'data/models/expense_model.dart';
import 'presentation/providers/dependency_providers.dart';
import 'presentation/screens/app_shell_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Hive Initialization ──────────────────────────────────
  await Hive.initFlutter();

  // Register Hive adapters (generated by hive_generator)
  Hive.registerAdapter(ExpenseModelAdapter());
  Hive.registerAdapter(CategoryModelAdapter());
  Hive.registerAdapter(BudgetModelAdapter());
  Hive.registerAdapter(AppSettingsModelAdapter());
  Hive.registerAdapter(PaymentMethodAdapter());
  Hive.registerAdapter(RecurringTypeAdapter());

  // Open all required boxes before the app starts
  await Future.wait([
    Hive.openBox<ExpenseModel>(AppConstants.expenseBoxName),
    Hive.openBox<CategoryModel>(AppConstants.categoryBoxName),
    Hive.openBox<BudgetModel>(AppConstants.budgetBoxName),
    Hive.openBox<AppSettingsModel>(AppConstants.settingsBoxName),
  ]);

  final container = ProviderContainer();
  await _runStartupTasks(container);

  // ── Run App ──────────────────────────────────────────────
  runApp(
    UncontrolledProviderScope(
      container: container,
      child: const ExpenseTrackerApp(),
    ),
  );
}

Future<void> _runStartupTasks(ProviderContainer container) async {
  try {
    await container.read(generateRecurringExpensesUseCaseProvider).call();
  } catch (error, stackTrace) {
    debugPrint('Recurring sync failed: $error');
    debugPrintStack(stackTrace: stackTrace);
  }
}

class ExpenseTrackerApp extends StatelessWidget {
  const ExpenseTrackerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: AppConstants.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      home: const AppShellScreen(),
    );
  }
}
